### ISSUE TITLE
Add a pygame.version attribute.

### ISSUE THREAD

**Issue by hodgestar** [CTPUG/pygame_cffi#58]
Pygame appears to have a `.version` attribute in the top-level package that, e.g., pyknic, relies upon.

**Comment by drnlm** [comment]
It's also important that the contents of pygame.version (ver, vernum and (in non-release builds) rev) are exposed as pygame.ver, pygame.vernum as well

At least some documentation recommends checking  pygame.ver, so that should be supported.

pygame.__version__ is also set to match pygame.version.ver as well.

**Comment by drnlm** [comment]
Closed by #73
